# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326106d23812f21a1cd3e2ca71a412b28f5f7d0be09b38cb0604b332695a44c66f45cdab65a4a7b12960c358a13dc9e957beb6f1c89bd5553eecd2ed4bfc9685

test:
  secret_key_base: 640ff2ce97955e0148af5fd104afabbb47708c6d2237cb098acb5832b0ec41fc6c71b319b163a0fa9235f3bc92a13c361c4b2e2b34d6229459d4421fd60e4a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
